### ISSUE TITLE
Error - No results found

### ISSUE THREAD

**Issue by Bancsis** [justchokingaround/lobster#234]
**Describe the bug**
I've tried installing several times but there are no results ever.

**To Reproduce**
Go through the windows installation process and search for a movie.

**Screenshots**
![image](https://github.com/user-attachments/assets/27cd853a-84b4-4730-b28b-29756c2cf41a)

**Desktop (please complete the following information):**
Windows 11 23H2

**Comment by luismendoza-ec** [comment]
Rabbit stream aka. VidCloud/VidStreams/UpCloud and some many more have changed the main method.

We are discussing possible solutions here:
https://github.com/drblgn/rabbit_wasm/issues/6#issuecomment-2450376653

**Comment by UnMolDeQuimica** [comment]
Hi @luismendoza-ec ! I see the linked issue is closed but the error persists on lobster. There is something we can do?

**Comment by FurqanHun** [comment]
> Hi @luismendoza-ec ! I see the linked issue is closed but the error persists on lobster. There is something we can do?

It was fixed a few weeks ago and works fine now… you do need to update lobster tho, if you installed directly from source then try `lobster --update` and if that doesn't work than just reinstall, or if installed through package manager then update it through that… it does take a bit longer for it to trigger mpv for some reason tho.

**Comment by UnMolDeQuimica** [comment]
Hi @FurqanHun and @daUnknownCoder!

Even reinstalling the script I still got the message Error - No results found. Trying to use lobster-rs did not fix the issue either. 

However, I found that doing a curl request to flixhq.to resulted in the following response:

```
<META HTTP-EQUIV="Pragma" CONTENT="no-cache"><META HTTP-EQUIV="Expires" CONTENT="-1"><html>Por causas ajenas a Vodafone, esta web no est�disponible</html>
```
This means that my internet provider is blocking the content, which explains the No results found error. 

That's weird, because I can access flixhq.to from firefox and chromium but not from the terminal, an incognito session with chromium or other programatic ways to connect to flixhq.to (like using the request package for python). 


Using a vpn solved the issue when streaming the content, but downloading it with the `-d` flag returns the following errors:

```
[in#1 @ 0x5a0c276b6a40] Error opening input: Server returned 5XX Server Error reply
Error opening input file https://cc.subsceness.xyz/2e/50/2e50f373f533b1821ca85145dbbd0972/spa-12.vtt.
Error opening input files: Server returned 5XX Server Error reply
```

Hope that is useful for you!

**Comment by FurqanHun** [comment]
@UnMolDeQuimica Interesting, seems like a DNS level blocking (i could be wrong tho), you can try switching to a different DNS provider system wide (or network wide).

Your ISP might be blocking access to flixhq or the current API server for Lobster (likely at the DNS level). To confirm, you can try visiting this API server in a browser and see if it works: https://testing-embed-decrypt.harc6r.easypanel.host/

```sh
        json_data=$(curl -s "https://testing-embed-decrypt.harc6r.easypanel.host/embed?embed_url=${embed_link}&referrer=https://${base}")
```
As for the downloading error, it's probably the subtitle site having some issues or just refusing the connection for some reason.

**Comment by Venkat2552004** [comment]
@UnMolDeQuimica Thanks, using VPN solved the issue. I though the movies that I am searching are not available at the source but after reading your comment, I understand what's wrong.

**Comment by daUnknownCoder** [comment]
@FurqanHun ok cool, so i was plugged out for a few days, now, i ran lobster and im on version `4.3.4`, now im on `4.3.5`:

```sh
╰─❯ lobster -i
Search Movie/TV Show: oppenheimer
^C⏎
```
^ an eternity later (!yes i ran `lobster -u`)

now i installed lobster-rs, its also on `4.3.5`
ran `lobster -u`

```sh
╰─❯ lobster-rs -i
Search Movie/TV Show: oppenheimer
Error: error sending request for url (https://flixhq.to/search/oppenheimer)

Caused by:
    0: client error (Connect)
    1: Connection reset by peer (os error 104)
    2: Connection reset by peer (os error 104)
```
^ 10-15 sec later

but:

![Image](https://github.com/user-attachments/assets/39313aa8-e197-42fa-bab8-a3e4592233de)

**Comment by FurqanHun** [comment]
@daUnknownCoder it's either flixhq blocking the connection (which i doubt based on the ss you provided) or a dns level block by your isp... and browsers can use different dns settings (like DNS over HTTPS) that bypass system wide dns, which might explain why it works in the browser but the ping doesn't go through...

**Comment by daUnknownCoder** [comment]
> @FurqanHun said: it's either flixhq blocking the connection (which i doubt based on the ss you provided) or a dns level block by your isp... and browsers can use different dns settings (like DNS over HTTPS) that bypass system wide dns, which might explain why it works in the browser but the ping doesn't go through...

wth is wrong now?
i changed dns server to cloudflare (1.1.1.1) and added a substiture dns google (8.8.8.8) but it still doesnt work, `ping flixhq.to` works now but lobster still wanna mess with me:

```py
╰─❯ ping flixhq.to
PING flixhq.to (2606:4700:3034::6815:47ae) 56 data bytes
64 bytes from 2606:4700:3034::6815:47ae: icmp_seq=1 ttl=56 time=508 ms
64 bytes from 2606:4700:3034::6815:47ae: icmp_seq=2 ttl=56 time=414 ms
64 bytes from 2606:4700:3034::6815:47ae: icmp_seq=3 ttl=56 time=512 ms
^C
--- flixhq.to ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 414.184/478.071/512.333/45.214 ms
```

```py
╰─❯ lobster -i
Search Movie/TV Show: oppenheimer
Error - No results found
╰─❯ lobster-rs -i
Search Movie/TV Show: oppenheimer
Error: error sending request for url (https://flixhq.to/search/oppenheimer)

Caused by:
    0: client error (Connect)
    1: Connection reset by peer (os error 104)
    2: Connection reset by peer (os error 104)
```

**Comment by FurqanHun** [comment]
@daUnknownCoder the only thing left is server closing the connection from your ip, lobster works fine for me, i did notice the server closing the connection but it didn't affect the playback... tho for lobster-rs at first i got some other var error which fixed itself when i restarted the terminal...

you can run lobster and lobster-rs `--debug` flag that can help in understanding it, you can also try to run it with a vpn...

**Comment by daUnknownCoder** [comment]
so ig, whenever i use lobster, i get `no results found` 8/10 times (even lobster-rs)

https://github.com/user-attachments/assets/e5043359-58c1-4a75-87bb-770d23133db4

**Comment by justchokingaround** [comment]
#259
