### ISSUE TITLE
--height option is currently not supported on this platform

### ISSUE THREAD

**Issue by Bancsis** [justchokingaround/lobster#33]
I am receiving this error when trying to search for a movie:
      --height option is currently not supported on this platform

I have installed all the dependencies and followed the setup process exactly.

![image](https://user-images.githubusercontent.com/56519024/196772932-595256f3-bd5d-4c9b-874c-644be983ad01.png)

Edition: Windows 11 Pro
Version: 21H2
OS Build: 22000.1098

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/a7caf6cd689163f8b037137b52ef603f044bd319
run `lobster -U` to update

**Comment by Bancsis** [comment]
It's working on my MacBook but still not on Windows 11. 

The height error is not there anymore however it just gets hung up now.
I did a re-clone and pulled down. 
lobster -U doesn't seem to work either
![image](https://user-images.githubusercontent.com/56519024/197260603-ef6eb3f1-a3a2-4f39-a566-a63614bd94b3.png)

**Comment by justchokingaround** [comment]
try removing it completely and reinstalling using the instructions in the readme

**Comment by Bancsis** [comment]
Same issue although I can't seem to do `irm get.scoop.sh | iex`

![image](https://user-images.githubusercontent.com/56519024/197290039-d7e9a8b0-5b22-477f-894b-d138235fe9c2.png)

**Comment by justchokingaround** [comment]
the SetExecution and the next command after it need to be run in powershell check the readme

**Comment by Bancsis** [comment]
My mistake, still getting hung up when searching for movie

**Comment by Bancsis** [comment]
Working now
